# @File  : constant.py
# @Author: LiuXingsheng
# @Date  : 2019/7/29
# @Desc  :

FRAME_CORRECT = 1
FRAME_INCORRECT = 2
FRAME_LESS = 3
FRAME_MORE = 17
FRAME_BOTTOM = 4
FRAME_WITHOUTFRAME = 5

TYPE_COMPLT = 6
TYPE_BLANK = 7
TYPE_FOCUS = 8
TYPE_ZUOYOUFENGE =9
TYPE_FENGEXIAN = 10
TYPE_WENKEGUOCHANG = 11
TYPE_SHUBENFANYE = 12
TYPE_DIANJITUXING = 13
TYPE_LIKESHI = 14
TYPE_LIKEBUSHI = 15
TYPE_WENKESHI = 16

